sudo: required

services:
  - docker
  
before_install:
 - docker login --username=$U --password=$P --email=$E
 
script: 
 - docker build -t infrastructor/ubuntu-sshd:0.0.2 . 
 - docker push infrastructor/ubuntu-sshd:0.0.2
